### ISSUE TITLE
Problem Renaming Repos

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#180]
## Description

When a repo is renamed it does not appear to be changing both the database and the filesystem correctly.  It appears to work temporarily, but then it's almost like there is a reversion afterward.

If the bug can be replicated, update the estimate to reflect time to fix.

**Comment by jag3773** [comment]
More information:

Hi Jesse! Sorry for bothering you again. But I got error 500 again. This time I uploaded repo from tS, then transferred ownership to WA_Eurasia organization, and when I tried to rename it I got error 500 and now that repo is unreachable.

https://git.door43.org/WA_Eurasia/ru_luk_text_ulb
it should be https://git.door43.org/WA_Eurasia/ru_luk_text_ulb_L1

**Comment by ethantkoenig** [comment]
Is there anyway to see the logs for the 500 error?

**Comment by jag3773** [comment]
I don't see anything getting logged for it.  Here is the filesystem tree for that org:
```
wa_eurasia/
├── ru_luk_text_ulb_l1.git
├── ru_luk_text_ulb_l2.git
├── ru_mat_text_ulb_l1.git
├── ru_mat_text_ulb_l2.git
├── ru_mrk_text_ulb_l1.git
├── ru_mrk_text_ulb_l2.git
├── ru_rev_text_ulb_l1.git
├── ru_rev_text_ulb_l2.git
├── ru-ta-translate-vol1.git
├── ru-ta-translate-vol2.git
├── ru-tq.git
└── ru-tw.git
```

**Comment by richmahn** [comment]
The error in the log that is being returned when you try to rename it from ru_luk_text_ulb to ru_luk_text_ulb_l1 is:

```[root@ip-172-31-38-86 wa_eurasia]# 2017/05/22 14:10:40 [...ters/repo/setting.go:74 SettingsPost()] [E] NewRepoRedirect: Error 1062: Duplicate entry '4746-ru_luk_text_ulb' for key 'UQE_repo_redirect_S'```

It looks like an primary key issue, yet it is still trying to save the old name.

**Comment by richmahn** [comment]
The problem seems to lie in how when you rename a repo, it creates a redirect to the new repo (for example git.door43.org/richmahn/test renamed to git.doro43.org/richmahn/test2 will still allow someone to go to richmahn/test and it will redirect to test2). It looks like before the site update the  old name of a renamed repo got used again, and then when wanting to rename that one, it caused two repos to have the same redirect. Can't reproduce it now so looks like when a new repo is created with an old name (but no longer exists) that redirect gets removed.

I have cleared the repo_redirect table. I tried to reproduce by making a repo, e.g. testrepo, rename it, e.g. testreponew, make a new repo with the old name, e.g. testrepo, and renaming that one, e.g. testreponew2....all works well.

**Comment by richmahn** [comment]
Restored redirects for Door43 and Door43-Catalog repos due to hyphen in name change. I guess this redirect is a new feature and was caused by a primary key issue, but wasn't able to reproduce with a new repo. User who had this problem reports there are no problems now.

**Comment by richmahn** [comment]
Restored redirects for Door43 and Door43-Catalog repos due to hyphen in name change. I guess this redirect is a new feature and was caused by a primary key issue, but wasn't able to reproduce with a new repo. User who had this problem reports there are no problems now.
