### ISSUE TITLE
Migrate ULB and UDB Issues

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#197]
We need to migrate the ULB and UDB source repositories from Github to DCS.

Locations

* https://github.com/Door43/ulb-en should migrate to https://git.door43.org/Door43/en_ulb
* https://github.com/Door43/udb-en should migrate to https://git.door43.org/Door43/en_udb

The *key* here is that we want to migrate the **issues**.  I setup a DCS migration for the ULB which worked fine, but we need to get the issues migrated.

Relevant upstream issue is closed, https://github.com/gogits/gogs/issues/809, but it doesn't look like it has been implemented.

Possibly https://github.com/mruschmann/migrate-gitlab-gogs could be modified to read from Github and push over into DCS?

**Comment by jag3773** [comment]
@ethantkoenig Let me know what your thoughts are on this.  We will need to schedule the actual migration time so that the content team can pause work on Github and shift over to DCS.  In the meantime any work we can do upfront to make that migration window small would be great.

**Comment by ethantkoenig** [comment]
@jag3773 Probably a just writing our own Python script would be easiest; we're basically just need to make calls to the Github API and our DCS/gitea API.

A few questions:
- Which of the following must be preserved during migrations?
  - labels
  - comments
  - assignees
  - milestones
- Will the repos have already been created on DCS before we migrate issues? If not, then whoever runs this script will need all of the credentials so that the repos will belong to the correct user(s).

**Comment by ChrisJarka** [comment]
@neutrinog - I believe that there is a resounding YES to these -

Which of the following must be preserved during migrations?

- labels
- comments
- assignees
- milestones

**Comment by pohlig** [comment]
I agree with Chris; we want all those things if it can possibly be done.
Thanks

**Comment by jag3773** [comment]
@ethantkoenig Yes, we want that information.  I've created both repos as listed in the OP.  This task is strictly for migrating the Issues.

There are no milestones in either of the source repositories.

For users, can you please create a mapping?  Most of the usernames are probably similar, but if there are any that you can't find a match for, post them here and we will get you a match.

**Comment by jag3773** [comment]
@ethantkoenig How is this coming?  When do you expect to have a script functional?  We are moving from Github to DCS on Friday.  The issues can transfer later if you're not ready yet.

**Comment by ethantkoenig** [comment]
@jag3773 I've haven't been able to spend much time on this yet, I should be able to make more progress sometime this week or weekend.

**Comment by jag3773** [comment]
@ethantkoenig Just FYI that I disabled the Issue queues in DCS so that no one manually creates issues in those repos.  The hope is that when you copy the issues over from Github they will have the same issue number in DCS, which should preserve any relationships based on issue numbers.

Once you have the script ready, make sure to enable the Issue trackers in DCS before you run it.

**Comment by ethantkoenig** [comment]
@jag3773 A few questions:

1. Unless the runner of the script has everyone's DCS credentials, we won't be able to preserve who created issues (i.e. unless I have user X's DCS credentials, I cannot create a DCS issue that will be attributed to user X). The best we can do is to prepend `userXYZ open this issue at <timestamp>:` to each issue description (and something similar for comments). It this acceptable?
2. Can I assume label names are the same in Github and DCS. If not, how do I associate Github labels with their DCS counterparts?
3. What if there is a Github label for which a DCS counterpart does not exist? I cannot create a label for a DCS repo unless I have write-access to that repo. (This could be solved if the script is run with admin credentials instead of mine).

**Comment by jag3773** [comment]
1. That's ok, prepend the statement as you suggested.

2-3. I'll give you write access to the repo. They are brand new so all the labels will need created.

**Comment by ethantkoenig** [comment]
There is a bug in the API for adding labels to issues. I'll made a fix (https://github.com/go-gitea/gitea/pull/2048), but unfortunately I won't be able to run my script until the fix makes it way to our DCS instance. We should make sure this fix is a part of the #203 release.

**Comment by ethantkoenig** [comment]
@jag3773 Also, do any of the Github repos have pull-requests? If so, should I create dummy issues so that issue numbers are preserved?

**Comment by jag3773** [comment]
Good point, yes, they both have prs and dummy issues are a great idea.
