### ISSUE TITLE
Fail to Commit in web editor

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#206]
Getting this on some repos:
![failtocommit](https://user-images.githubusercontent.com/107731/27549992-331f3214-5a5b-11e7-8a20-4eac55e78467.png)

**Comment by richmahn** [comment]
Looks like multiple people editing the repo is causing the way Gogs works with a checked-out copy to fail. This may be because before I/we came along to make the web editor for Gogs, it wasn't anticipated to make changes through Gogs! Before the web edit to edit/delete/add files, it just checked out repos to read them, not change them in a temp dir. Now that we change them the same way it checks them out to read the repo, we could be getting collisions (for this issue I saw multiple files deleted but it never successfully committed so it was still in a commit/merge phrase of some sort). 

We probably need to make a change upstream to actually do a clean checkout, make changes, commit, and delete the checked out repo. Right now it keeps trying to work with the same checked out repo in the temp directory (/tmp/gitea-local-repo) for multiple reads, writes, deletes, etc. Probably the reason for this issue. 

@ethantkoenig Have you ever heard of people mentioning this? I assume most people use Gitea for personal use and don't have multiple people committing. Do you think I'm right in my assumptions? Does the whole way it interfaces with git on the command line on the server-side need to be improved?

**Comment by jag3773** [comment]
For now, our temporary fix of a crontab to clear out the /tmp directory is sufficient.  The code issue will be tracked in the upstream issue.

Our fix is:
```
[root@ip-172-31-38-86 ~]# crontab -l
0 0  * * *  /bin/rm -rf /tmp/gitea-local-repo/*
```
