### ISSUE TITLE
Repo Search

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/gogs#6]
We need a way to search for repos in Gogs.  Currently, the "Explore" feature is the only way to see other repos, which makes it hard to find things.

Ideally, we could have these features:
- [x] General search box
- [ ] Ability to search for repos in a given language
- [ ] Ability to search for repos for a given project
- [ ] Any combination of the above

Essentially, something that operates like Github's issue search would be nice.

Technically this may be implemented as adding AND or OR where there are spaces in the search string.  Prioritize AND over OR operators.

For books of the Bible, add a mapping from the USFM shortcodes to the full names (e.g. Luke -> luk).

**Comment by richmahn** [comment]
This is talked about here; https://github.com/gogits/gogs/issues/13

**Comment by richmahn** [comment]
Discussed with Gogs developer. He is looking into how to make this search feature for repos. Hoping he has time during Spring break to do it since he is a student.

**Comment by richmahn** [comment]
There is now a general search box on test.door43.org:3000. It searched with a %<term>% LIKE in the database, so searching by languages can be done by putting "-fr" in the search field, or a project by "uw-obs" or just "-obs". At least we have that for now. If we start making changes to have other search fields for actual languages and projects, it may be harder to merge down the line, but would be good if someone could select a language by name or a book of the Bible by name (rather than code) . Thoughts?

**Comment by jag3773** [comment]
We do want to enhance the search, but we need to define it better first.  I'll move this into the backlog for the moment and we'll revisit it later.

**Comment by jag3773** [comment]
For now, the /explore page will suffice.  Better search capability will be built into the live site.
